### ISSUE TITLE
Expose DuckDB `COPY` Command to Postgres

### ISSUE THREAD

**Issue by philippemnoel** [paradedb/pg_analytics#104]
### What feature are you requesting?

An easy way to load data between DuckDB and external files is via the `COPY` command. We should expose it, as it is especially difficult to load data into Postgres that's in format like Parquet aside from via the FDW.

### Why are you requesting this feature?

See above^

### What is your proposed implementation for this feature?

See here: https://duckdb.org/docs/sql/statements/copy.html for reference. Expose the command in a similar fashion to how we expose other DuckDB commands.

### Full Name:

Philippe Noël

### Affiliation:

ParadeDB

**Comment by rebasedming** [comment]
Duplicate of #107
