### ISSUE TITLE
Non-lossy type conversion

### ISSUE THREAD

**Issue by sardination** [paradedb/pg_analytics#12]
**What**
Currently, conversion between datafusion and postgres types is lossy, and we don't want it to be!

**Why**
In order to support joins and function overloading, we need to have exact type conversion. To search up a specific function in postgres, for example, we need to search by function signature. If the type conversion is lossy, then the signature will not be the same between creation and searching.

**How**
Update type translators.

**Comment by philippemnoel** [comment]
Closing these as we're archiving this repository for good
