### ISSUE TITLE
Add `pg_analytics` docs to the README

### ISSUE THREAD

**Issue by Weijun-H** [paradedb/pg_analytics#127]
### What feature are you requesting?

Migrate the documents related to the `pg_analytics` to its repo

### Why are you requesting this feature?

It would be beneficial for the maintenance of 'pg_analytics' to avoid creating multiple pull requests, one for code and another for documentation.

### Full Name:

Weijun Huang

### Affiliation:

Individual

**Comment by philippemnoel** [comment]
Done!
