### ISSUE TITLE
Add Support for PG17

### ISSUE THREAD

**Issue by philippemnoel** [paradedb/pg_analytics#130]
### What feature are you requesting?

PG17 is being released and is now supported in `pgrx`. We should add support for it!

### Why are you requesting this feature?

Support all official PGDG versions

### What is your proposed implementation for this feature?

Add it to the test suite and see what needs updating

### Full Name:

Philippe Noël

### Affiliation:

ParadeDB

**Comment by Weijun-H** [comment]
stalled by #135

**Comment by philippemnoel** [comment]
As part of this, I think we'll want to default to PG17 in our `Cargo.toml` as well
