### ISSUE TITLE
'time_bucket' function clashes with timescaledb

### ISSUE THREAD

**Issue by ssidorenko** [paradedb/pg_analytics#150]
### What happens?

When creating extension on a server with timescaledb already created, it fails because the function name `time_bucket` is already taken.

### To Reproduce

- Install timescaledb
- Install pg_analytics

### OS:

Linux x64 (Alma Linux 9.4)

### ParadeDB Version:

0.1.4

### Are you using ParadeDB Docker, Helm, or the extension(s) standalone?

ParadeDB pg_analytics Extension

### Full Name:

Semion Sidorenko

### Affiliation:

Sidorenko Consulting

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include the code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configurations (e.g., CPU architecture, PostgreSQL version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by philippemnoel** [comment]
Hey @ssidorenko! We haven't really invested effort in making `pg_analytics` compatible with Timescale. What is your use case?

If you'd like to submit a patch for this, we'd love. But otherwise I'm going to close this as a non-issue.

**Comment by cobolbaby** [comment]
Why install third-party extensions in the public schema? Is there a way to configure them to be installed in the default schema?

**Comment by phyk** [comment]
We have a use case where we want to have a delta table managed by pg_analytics on the one hand and streaming data ingested into the postgres on the other hand. From what I can see pg_analytics does not support a) streaming data efficiently and b) providing a way to do real time analytics as timescaledb does.

For that reason a combination of both would be beneficial?

**Comment by phyk** [comment]
Cross linked the issue here https://github.com/timescale/timescaledb/issues/7387

**Comment by philippemnoel** [comment]
If this is required for Timescale compatibility, we're happy to rename the functions/remove them. I dont' think they're used actively today.

**Comment by ssidorenko** [comment]
> We have a use case where we want to have a delta table managed by pg_analytics on the one hand and streaming data ingested into the postgres on the other hand. From what I can see pg_analytics does not support a) streaming data efficiently and b) providing a way to do real time analytics as timescaledb does.
> 
> For that reason a combination of both would be beneficial?

We had a very similar situation. For unrelated reasons, I ended up going for a different architecture that did not use `pg_analytics`, but at the time it sure would have been nice to be able to have both extensions in the same DB. I had to provision separate database instances instead one for timescale and one for pg_analytics, and use FDWs or Trino for cross-db querying.

**Comment by philippemnoel** [comment]
I removed the `datetime` function, since it wasn't being used.
