### ISSUE TITLE
UDF update and deletion

### ISSUE THREAD

**Issue by sardination** [paradedb/pg_analytics#16]
**What**
Upon `CREATE OR REPLACE FUNCTION` or `DELETE FUNCTION` we need to delete all functions with the corresponding signature and allow them to be reloaded when explicitly called.

**Why**
Right now, if a UDF is updated or deleted, the DataFusion context will not reflect this if the function has already been used once during the session.

**How**
Use the function name to delete all functions with the corresponding name from the context registry. Once overloaded functions are supported, this will become more complex, as it will require finding the right function by signature as well.

Need this PR to become available in the next release of DataFusion: https://github.com/apache/arrow-datafusion/pull/9239

**Comment by philippemnoel** [comment]
Closing these as we're archiving this repository for good
