### ISSUE TITLE
Doc: How do I configure the access_key and access_secret?

### ISSUE THREAD

**Issue by cobolbaby** [paradedb/pg_analytics#161]
### What happens?

Where do I configure the access_key and access_secret? Isn't a key required to access S3?

### To Reproduce

```
CREATE EXTENSION pg_analytics;
CREATE FOREIGN DATA WRAPPER parquet_wrapper HANDLER parquet_fdw_handler VALIDATOR parquet_fdw_validator;

-- Provide S3 credentials ???
CREATE SERVER parquet_server FOREIGN DATA WRAPPER parquet_wrapper;

-- Create foreign table with auto schema creation
CREATE FOREIGN TABLE fact_pca_yield_statistics_parquet ()
SERVER parquet_server
OPTIONS (files 's3://infra-oss.ipt.inventec.net/databricks/BDC/IPT_PG/bdc/dw/fact_pca_yield_statistics/fact_pca_yield_statistics-full.parquet');
```

### OS:

x86_64

### ParadeDB Version:

0.1.4

### Are you using ParadeDB Docker, Helm, or the extension(s) standalone?

ParadeDB pg_analytics Extension

### Full Name:

Cobol

### Affiliation:

Inventec

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include the code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configurations (e.g., CPU architecture, PostgreSQL version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by philippemnoel** [comment]
Docs are here: https://docs.paradedb.com/integrations/object_stores/s3
