### ISSUE TITLE
Support UDF overloading

### ISSUE THREAD

**Issue by sardination** [paradedb/pg_analytics#17]
**What**
Right now, only one UDF can be registered under a single name and used on columnar tables. We want multiple overloaded UDFs to be able to be used for different use cases in a columnar table query.

**Why**
Function overloading is a built-in feature of Postgres. We should support it!

**How**
Infer the signature from the logical plan, pass the signature along with the function name as an argument to the UDF, use non-lossy type conversion (#826) to get the corresponding function OID and call the function.

**Comment by philippemnoel** [comment]
Closing these as we're archiving this repository for good
