### ISSUE TITLE
Invalid Input Error: Secret provider 'service_principal' not found for type 'azure'

### ISSUE THREAD

**Issue by dgaudet** [paradedb/pg_analytics#175]
### What happens?

I receive an error when attempting to create a forgein table to the azure data lake using a service principal for credentials.

This is the error:```Invalid Input Error: Secret provider 'service_principal' not found for type 'azure'```

### To Reproduce

I start up a brand new paradedb using docker and exec into it:
```
docker run --name paradedb -e POSTGRES_PASSWORD=password paradedb/paradedb
docker exec -it paradedb psql -U postgres
```

Then I setup the Foreign data wrapper, create a server and user mapping:
```
psql (16.4 (Debian 16.4-1.pgdg120+2))
Type "help" for help.

postgres=# CREATE FOREIGN DATA WRAPPER parquet_wrapper
HANDLER parquet_fdw_handler
VALIDATOR parquet_fdw_validator;
CREATE FOREIGN DATA WRAPPER

postgres=# CREATE SERVER parquet_server
FOREIGN DATA WRAPPER parquet_wrapper;
CREATE SERVER

postgres=# CREATE USER MAPPING FOR public
SERVER parquet_server
OPTIONS (
  type 'AZURE',
  provider 'SERVICE_PRINCIPAL',
  tenant_id '<my tennant id>',
  client_id '<my client id>',
  client_secret '<my client secret>,
  account_name '<my storage account name>'
);
CREATE USER MAPPING
```

Then I try to setup the foreign table:
```
postgres=# CREATE FOREIGN TABLE parquet_table ()
SERVER parquet_server
OPTIONS (files 'az://<actual path>/*.parquet');
ERROR:  Invalid Input Error: Secret provider 'service_principal' not found for type 'azure'
```

### OS:

macOSX

### ParadeDB Version:

v0.2.3

### Are you using ParadeDB Docker, Helm, or the extension(s) standalone?

ParadeDB Docker Image

### Full Name:

Dean Gaudet

### Affiliation:

Enverus

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include the code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configurations (e.g., CPU architecture, PostgreSQL version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by philippemnoel** [comment]
Thanks for your report -- We'll investigate.

**Comment by kysshsy** [comment]
The error is occured in duckdb.Seem current dev branch is fine because it has a newer version of duckdb-rs https://github.com/duckdb/duckdb/pull/13902

**Comment by kysshsy** [comment]
The error is occured in duckdb. seem current dev branch is fine because it has a newer version of duckdb-rs https://github.com/duckdb/duckdb/issues/1583

**Comment by philippemnoel** [comment]
Hi @dgaudet. As @kysshsy said, this is fixed in `dev`. We'll do a release and it'll go out in `v0.2.4`. Thank you for your patience!
