### ISSUE TITLE
Overriding HTTP headers from DDL and environment

### ISSUE THREAD

**Issue by tucnak** [paradedb/pg_analytics#180]
### What feature are you requesting?

There's private datasets in Parquet format, or otherwise sitting behind a license, on [Huggingface](https://huggingface.co/datasets). We're normally able to list individual part files, read them over API, and provide to pg_analytics, however if the dataset is private, these requests but also reads both require a Bearer token.

### Why are you requesting this feature?

See #179 for context on how we use pg_analytics for text dataset ETL.

### What is your proposed implementation for this feature?

Some kind of option for specifying HTTP headers that pg_analytics would add to its HTTP requests, possibly interpolating variables from environment (these often would be secrets!)

### Full Name:

Ilya Kowalewski

### Affiliation:

The Stone Cross Foundation

**Comment by philippemnoel** [comment]
You can see the instructions for passing tokens here: https://duckdb.org/2024/05/29/access-150k-plus-datasets-from-hugging-face-with-duckdb.html

**Comment by tucnak** [comment]
Wow, I never knew DuckDB could do this natively, & I never knew pg_analytics exposed any of it... Does this mean that there's some API that I can use to run these seemingly necessary duck-SQL commands from psql, or are they not necessary in the first place?

> Secrets can be created using the [CREATE SECRET SQL statement](https://duckdb.org/docs/sql/statements/create_secret.html). Secrets can be temporary or persistent. Temporary secrets are used by default – and are stored in-memory for the life span of the DuckDB instance similar to how settings worked previously. Persistent secrets are stored in unencrypted binary format in the `~/.duckdb/stored_secrets` directory. On startup of DuckDB, persistent secrets are read from this directory and automatically loaded.
>
> https://duckdb.org/docs/configuration/secrets_manager.html

So if I had a DuckDB installation, I could simply copy `~/.duckdb` and pg_analytics would use it? On a different note, simply eing able to load datasets via `hf://` is super, wish I knew this before I had implemented the procedures to do it in the first place. 🤣

**Comment by philippemnoel** [comment]
> Wow, I never knew DuckDB could do this natively, & I never knew pg_analytics exposed any of it... Does this mean that there's some API that I can use to run these seemingly necessary duck-SQL commands from psql, or are they not necessary in the first place?
> 
> > Secrets can be created using the [CREATE SECRET SQL statement](https://duckdb.org/docs/sql/statements/create_secret.html). Secrets can be temporary or persistent. Temporary secrets are used by default – and are stored in-memory for the life span of the DuckDB instance similar to how settings worked previously. Persistent secrets are stored in unencrypted binary format in the `~/.duckdb/stored_secrets` directory. On startup of DuckDB, persistent secrets are read from this directory and automatically loaded.
> > https://duckdb.org/docs/configuration/secrets_manager.html
> 
> So if I had a DuckDB installation, I could simply copy `~/.duckdb` and pg_analytics would use it? On a different note, simply eing able to load datasets via `hf://` is super, wish I knew this before I had implemented the procedures to do it in the first place. 🤣

Please check the documentation here: https://github.com/paradedb/pg_analytics/blob/dev/docs/object_stores/huggingface.mdx. I think it should cover this.

**Comment by tucnak** [comment]
Thank you!
