### ISSUE TITLE
Store command IDs (i.e. `cmin`) with tuples

### ISSUE THREAD

**Issue by rebasedming** [paradedb/pg_analytics#19]
**What**
Using the same approach we have to store a tuple's `xmin`/`xmax` we should also be storing a tuple's `cmin`/`cmax`.

**Why**
While `xmin`/`xmax` determine if a tuple is visible across transactions, `cmin`/`cmax` determine if a tuple is visible within the same transaction. This is probably necessary for subtransaction/savepoint support.

**How**

**Comment by philippemnoel** [comment]
Closing these as we're archiving this repository for good
