### ISSUE TITLE
Introduce debug functions to `pg_analytics`

### ISSUE THREAD

**Issue by rebasedming** [paradedb/pg_analytics#2]
**What**
Users are getting `table not found` errors that are tough to debug because we don't have access to their DB. We should introduce a function that prints the DataFusion schema, i.e.

```sql
SELECT * FROM paradedb.parquet_schema();
-- Returns a table with all DataFusion tables and their respective schemas
```

**Why**
For debugging

**How**

**Comment by philippemnoel** [comment]
Closing these as we're archiving this repository for good
