### ISSUE TITLE
Unexpected behavior with large precision/scales for numerics

### ISSUE THREAD

**Issue by rebasedming** [paradedb/pg_analytics#24]
**Bug Description**
Large precision/scales on numerics cause strange errors to be thrown.

I noticed that when we store numerics in Datafusion, they get multiplied by the scale. For instance if I have a `numeric(5,2)` and I store the value `1.01`, it gets stored as `101`. When we retreive the numeric value back we scale it down, but this seems to cause some problems where if you have an extremely large scale (say `30`) then you're multiplying the number by `10^30` before storing it in Datafusion and that causes overflow problems.

**How To Reproduce**
```sql
CREATE TABLE t (a numeric(30,30)) USING parquet;
pg_analytics=# insert into t values (0.01);
ERROR:  Precommit callback failed: Delta(Arrow { source: ParseError("parse decimal overflow") })
```

**Proposed Fix**

**Comment by philippemnoel** [comment]
Closing these as we're archiving this repository for good
