### ISSUE TITLE
Show users a better error message for complex updates

### ISSUE THREAD

**Issue by rebasedming** [paradedb/pg_analytics#25]
**What**
Currently, UPDATE clauses are not supported. If the user executes a query that starts with UPDATE, they see a clean error message. But if they execute an UPDATE nested inside another query, like a CTE, they'll see a confusing error that just says `failed to fetch tuple being updated`.

**Why**
So users don't think this is an unexpected bug.

**How**
The reason they're seeing this is because the table access method is failing behind the scenes on UPDATE clauses. The error comes before the update tableAM method is hit, and after the scan table method runs. I suspect it has to do with the fact that Postgres is looking for the tuple in block storage with a ctid, but we don't store tuples there.

I also noticed that this error message doesn't show up on Postgres 12.

**Comment by Abdi-29** [comment]
I'd like to work on this issue if it's not taken yet

**Comment by philippemnoel** [comment]
> I'd like to work on this issue if it's not taken yet

Absolutely, feel free to :) I would suggest working on features in `paradedb/paradedb` over features in `paradedb/pg_analytics`, t hough

**Comment by Abdi-29** [comment]
Do you have some tips on issues I could work on for features in paradedb/paradedb?

**Comment by philippemnoel** [comment]
> Do you have some tips on issues I could work on for features in paradedb/paradedb?

Maybe these:

https://github.com/paradedb/paradedb/issues/890

https://github.com/paradedb/paradedb/issues/1061

**Comment by Abdi-29** [comment]
Thanks, I get the both of them

**Comment by philippemnoel** [comment]
Closing these as we're archiving this repository for good
