### ISSUE TITLE
Support timestamp with time zone

### ISSUE THREAD

**Issue by rebasedming** [paradedb/pg_analytics#26]
**What**
Support the `timestamptz` type

**Why**
`timestamptz` is a built-in Postgres type

**How**
I have a [branch](https://github.com/paradedb/paradedb/tree/feat/timestamptz) open for this. I'm blocked because DataFusion doesn't support the `AT TIME ZONE` clause which is used to query `timestamptz` columns. I've opened an [issue](https://github.com/apache/arrow-datafusion/issues/9580) for it in DataFusion.

**Comment by philippemnoel** [comment]
Closing these as we're archiving this repository for good
