### ISSUE TITLE
Fix foreign table `EXPLAIN`s

### ISSUE THREAD

**Issue by rebasedming** [paradedb/pg_analytics#45]
**What**

` EXPLAIN` queries over `pg_lakehouse` foreign tables are not working correctly for a few reasons:

1. Running `EXPLAIN` on a query that's fully pushed down to DuckDB returns the query plan of the foreign data wrapper, which isn't the actual query plan. This is because the FDW's query plan is only used if the query fails in the executor hook and falls back to the FDW.

For instance, `EXPLAIN SELECT COUNT(*)` returns

```sql
explain select count(*) from hits;
                          QUERY PLAN
--------------------------------------------------------------
 Aggregate  (cost=1.00..1.01 rows=1 width=8)
   ->  Foreign Scan on hits  (cost=0.00..1.00 rows=1 width=0)
         DuckDB Scan: SELECT * FROM public.hits
(3 rows)
```
Which would be the correct plain IF this query fell back to the FDW. In reality, this entire query is pushed down to DuckDB, so the query plan should be:

```sql
explain select count(*) from hits;
                          QUERY PLAN
--------------------------------------------------------------
DuckDB Scan: SELECT COUNT(*) FROM public.hits
(1 row)
```

2. `EXPLAIN` with options like `ANALYZE` is not working at all. This is due to the fact that
a) DuckDB does not recognize all the Postgres EXPLAIN options like `VERBOSE`, `COSTS`, etc.
b) `EXPLAIN ANALYZE` is not properly handled. Right now it throws an error.

**Why**
EXPLAIN should return the correct query plan.

**How**
Two ideas I've considered are:

1. Using the process utility hook to intercept all EXPLAIN queries. However, we still need to figure out how to handle EXPLAIN options not supported by DuckDB.
2. Convert the executor hook to a custom scan, which should make EXPLAIN queries work out of the box. However, I'm not sure about the scope of work that this would entail or if custom scans introduce unforeseen side effects to query performance.

**Comment by shamb0** [comment]
Hi @philippemnoel,

If it's open, could you please assign it to me? Thanks :)

**Comment by philippemnoel** [comment]
> Hi @philippemnoel,
> 
> If it's open, could you please assign it to me? Thanks :)

It was previously taken by @kysshsy in #64, but I haven’t heard much in a few weeks. If you want you can take it, but you probably want to build on top of what was done in #64 as it is a good start

**Comment by kysshsy** [comment]
@philippemnoel @shamb0  Sorry for the delay.

I'm busy with my job and wukong the last month, haha.

I would greatly appreciate it if you could resolve this issue based on my current work.
-----------
I am trying to introduce the parse and deparse functionalities from other libraries into pg_analytics, to extract the query Select * from t1; from the utility statement EXPLAIN SELECT * FROM t1;

pg_query.rs or sqlparser

1. pg_query.rs:
pros:
1. base on Postgres source code.

cons:
1. it can't compile with pg_analytics because duplicate global symbol in static library in pg_query.rs.
(actually I work on hiding or renaming those duplicate gloabl symbol to make it work.  I make it by changing pg_query's build.rs. But it's hacky. I use objcopy to rename all symbols with prefix_{origin_symbol}

2. sqlparser:
pros:
1. more flexible interface

cons:
1. introduce a parser that different from postgres.

**Comment by philippemnoel** [comment]
> @philippemnoel @shamb0 Sorry for the delay.
> 
> I'm busy with my job and wukong the last month, haha.
> 
> I would greatly appreciate it if you could resolve this issue based on my current work.
> 
> I am trying to introduce the parse and deparse functionalities from other libraries into pg_analytics, to extract the query Select * from t1; from the utility statement EXPLAIN SELECT * FROM t1;
> 
> pg_query.rs or sqlparser
> 
> 1. pg_query.rs:
>    pros:
>    base on Postgres source code.
>    cons:
>    it can't compile with pg_analytics because duplicate global symbol in static library in pg_query.rs.
>    (actually I work on hiding or renaming those duplicate gloabl symbol to make it work.  I make it by changing pg_query's build.rs. But it's hacky. I use objcopy to rename all symbols with prefix_{origin_symbol}
> 2. sqlparser:
>    pros:
>    more flexible interface
>    cons:
>    introduce a parser that different from postgres.
> 
> I think sqlparser would be a better choice now.

Yes, please use sqlparser. It's a very popular Postgres and has strong support for Postgres. I think it'll be perfect. Thank you for picking this back up <3
