### ISSUE TITLE
Add support for DuckDB Geospatial extensions

### ISSUE THREAD

**Issue by Mmoncadaisla** [paradedb/pg_analytics#46]
**What**
Now that DuckDB serves as `pg_lakehouse` query engine, it'd be very useful if it was possible to leverage both official and unofficial extensions in queries targeting foreign tables.

In our specific case we would be interested in https://github.com/isaacbrodsky/h3-duckdb & https://github.com/duckdb/duckdb_spatial/ 

**Why**
Unlock different use cases.

**Comment by Weijun-H** [comment]
I am glad to try this ticket.

**Comment by philippemnoel** [comment]
> I am glad to try this ticket.

Thank you!
