### ISSUE TITLE
Push down `quals` in foreign table scan

### ISSUE THREAD

**Issue by rebasedming** [paradedb/pg_analytics#47]
**What**
The `begin_scan` function of the foreign data wrapper ignores `quals`, which means that predicates are not pushed down to DuckDB in the case that the query falls back to the FDW scan.

**Why**
Pushing down quals will make queries that fall back to the FDW faster. Could be useful for federated joins.

**How**
Parse `quals` and add them to the DuckDB query. I believe the clickhouse_fdw has a good implementation for this.

**Comment by philippemnoel** [comment]
Solved by #39, thank you @kysshsy!
