### ISSUE TITLE
DATE_TRUNC('day', date_day) not supported

### ISSUE THREAD

**Issue by BigBerny** [paradedb/pg_analytics#49]
### What happens?

When running this query I get an error:
```
SELECT DATE_TRUNC('day', date_day), AVG("queryLatency")
FROM predictions
GROUP BY DATE_TRUNC('day', date_day)
```

Error:
`Query 1 ERROR at Line 1: : ERROR:  Column date_trunc has Arrow data type Date32 but is mapped to the BuiltIn(TIMESTAMPOID) type in Postgres, which are incompatible. If you believe this conversion should be supported, please submit a request at https://github.com/paradedb/paradedb/issues.`

Since DATE_TRUNC() is quite fundamental for many analysis, for whenever you want to group by day, week, month or year, it would be awesome if this could be fixed somehow.
Tools like Metabase often offer users a way to choose granularity of an analysis

### To Reproduce

Do a GROUP BY on DATE_TRUNC(). It happens with date and timestamp columns and also for 'week' etc.

### OS:

Ubuntu(?) with PostgreSQL 16.3

### ParadeDB Version:

0.8.3

### Full Name:

Janis

### Affiliation:

Typewise

### What is the latest build you tested with? If possible, we recommend testing by compiling the latest `dev` branch.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include the code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configurations (e.g., CPU architecture, PostgreSQL version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by philippemnoel** [comment]
@evanxg852000 I've reverted this PR as the tests were not passing. We simply had not noticed that the CI was not running
