### ISSUE TITLE
Show users a better error message for unsupported timestamp ranges

### ISSUE THREAD

**Issue by rebasedming** [paradedb/pg_analytics#5]
**What**
Datafusion only supports queries with timestamps from 1677 to 2262 (https://github.com/apache/arrow-datafusion/blob/b7f477237cc91bbdf90e655db181ca4f0a64fc25/datafusion/functions/src/datetime/common.rs#L34). When users try to query with a timestamp outside of this range i.e. `SELECT * FROM t WHERE a < '1650-01-01 01:01:01'::timestamp` they get a confusing error message about nanosecond overflow. We should intercept this error message and show them a more helpful one.

**Why**

**How**

**Comment by Abdi-29** [comment]
I fixed the issue in the arrow-rs and I'm waiting them to accept my pr

**Comment by philippemnoel** [comment]
https://github.com/apache/arrow-rs/pull/5730
