### ISSUE TITLE
Support `test-pg_analytics` in CI

### ISSUE THREAD

**Issue by Weijun-H** [paradedb/pg_analytics#60]
### What feature are you requesting?

Since the `pg_analytics` and `pg_lakehouse` have relocated here, 'test-pg_analytics' needs to be moved here as well.
https://github.com/paradedb/paradedb/blob/dev/.github/workflows/test-pg_analytics.yml

### Why are you requesting this feature?

It would benefit the testing.

### Full Name:

Weijun Huang

### Affiliation:

None

**Comment by philippemnoel** [comment]
Thank you for finding this oversight!
