### ISSUE TITLE
Update `pgrx` to the stable 0.12 version once it is released

### ISSUE THREAD

**Issue by Weijun-H** [paradedb/pg_analytics#66]
This feels unsafe. I'm not sure if we want to match all other cases to user mapping relation id. I made a PR to pgrx a while back to expose `USER_MAPPING_ID` to `pg_sys` but it would require we upgrade `pgrx`.

_Originally posted by @rebasedming in https://github.com/paradedb/pg_analytics/pull/37#discussion_r1712662854_

**Comment by philippemnoel** [comment]
Great idea! I chatted with the `pgrx` folks and it should release within the week (As of August 12, 2024)
